import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import worker from '../worker.mjs';
const binding=db=>({async batch(statements){db.exec("BEGIN");try{const out=[];for(const statement of statements)out.push(await statement.run());db.exec("COMMIT");return out}catch(e){db.exec("ROLLBACK");throw e}},prepare(sql){let values=[];return{bind(...v){values=v;return this},async first(){return db.prepare(sql).get(...values)},async all(){return{results:db.prepare(sql).all(...values)}},async run(){return db.prepare(sql).run(...values)}}}});
const request=(path,method='GET',data,key)=>new Request('https://demo.example/api/rooms'+path,{method,headers:{Origin:'https://demo.example',...(key?{Authorization:'Bearer '+key}:{}),...(data?{'Content-Type':data instanceof Uint8Array?'image/jpeg':'application/json'}:{})},...(data?{body:data instanceof Uint8Array?data:JSON.stringify(data)}:{})});
test('shared records persist across visitors, conflict safely, preserve comments and constrain phone links',async()=>{
 const db=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+f,'utf8'));const files=new Map(),env={DB:binding(db),BUCKET:{async put(k,b){files.set(k,b)},async get(k){return files.has(k)?{body:files.get(k)}:null},async delete(k){files.delete(k)}}};
 const state={qty:24,reserve:80,reason:'Ageing stock',eligibility:'clear',stage:'draft',bid:90,rfqQty:120,rfqProduct:'Bags',rfqCity:'Jaipur',rfqDate:'2026-11-08',rfqCreated:false,quote:112,dispatchFrom:'2026-11-01',dispatchTo:'2026-11-02'};
 const call=(p,m,d,k)=>worker.fetch(request(p,m,d,k),env);
 const created=await call('','POST',{state});assert.equal(created.status,201);const r=await created.json();const path='/'+r.id;
 assert.equal((await call(path)).status,403);assert.equal((await call(path,'GET',null,'wrong')).status,403);
 assert.deepEqual((await (await call(path,'GET',null,r.key)).json()).state,state);
 const second={...state,qty:30};assert.equal((await call(path,'PUT',{version:1,state:second,actor:'seller'},r.key)).status,200);
 assert.equal((await call(path,'PUT',{version:1,state:{...state,qty:11},actor:'seller'},r.key)).status,409);
 assert.equal((await (await call(path,'GET',null,r.key)).json()).state.qty,30);
 const c=await (await call(path+'/handoff','POST',null,r.key)).json();const phone=await (await call(path,'GET',null,c.key)).json();assert.equal(phone.captureOnly,true);assert.equal(phone.state.reserve,undefined);
 assert.equal((await call(path,'PUT',{version:2,state},c.key)).status,403);
 const jpeg=new Uint8Array([255,216,255,224,0,16,74,70,73,70,0,1]);const up=await call(path+'/photos?slot=0','POST',jpeg,c.key);assert.equal(up.status,201);const photo=await up.json();
 assert.equal((await call(path+'/photos/'+photo.id,'GET',null,r.key)).status,200);
 assert.equal((await call(path+'/photos/'+photo.id)).status,403);
 const newState={...second,stage:'pool',rfqCreated:true};assert.equal((await call(path,'PUT',{version:2,state:newState,actor:'seller'},r.key)).status,200);let snap=await (await call(path,'GET',null,r.key)).json();assert.equal(snap.history.length,1);assert.equal(snap.photos.length,1);
 assert.equal((await call(path,'PUT',{version:3,state:{...newState,stage:'bid'},actor:'buyer'},r.key)).status,200);
 assert.equal((await call(path,'PUT',{version:4,state:{...newState,stage:'bid',qty:1},actor:'seller'},r.key)).status,409);
 assert.equal((await call(path+'/photos?slot=1','POST',jpeg,c.key)).status,409);
 db.prepare('UPDATE demo_captures SET expires_at = 0').run();assert.equal((await call(path,'GET',null,c.key)).status,403);
 assert.equal(db.prepare('SELECT COUNT(*) n FROM review_comments').get().n,0);db.close();
});
