import React,{useState} from 'react';
import {ArrowRight,Plus,Package,ShoppingBag} from 'lucide-react';
import {businessMetrics} from './business-metrics.mjs';
import {nextStep} from './order-journey.mjs';
import {useLanguage} from './i18n.jsx';
import './business-dashboard.css';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n/100);
function Metric({label,value,note}){return <div className="business-metric"><dt>{label}</dt><dd>{value}</dd><p>{note}</p></div>}
function ComparisonEditor({orders,nav,command,titleFor}){
 const[chosen,setChosen]=useState(orders[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),o=orders.find(o=>o.id===chosen);
 return <details className="comparison-editor"><summary>Add or update a purchase comparison</summary><p>Use an alternative quote or recent purchase for the same product, condition and quantity. Include delivery and all charges.</p>{!orders.length?<p>Comparisons become available when you have a surplus purchase order.</p>:<><label className="field"><span>Purchase order</span><select value={chosen} onChange={e=>{setChosen(e.target.value);setSaved(false)}}>{orders.map(o=><option key={o.id} value={o.id}>{titleFor(o)} · {o.qty} units · {o.id.slice(0,6)}</option>)}</select></label>{o&&<form key={o.id+'-'+(o.buyerComparison?.at||0)} className="form" onSubmit={async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await command({type:'order.comparison',id:o.id,quantity:o.qty,unitPrice:Math.round(Number(v.unitPrice)*100),basis:v.basis,comparable:v.comparable==='on'});setSaved(true)}catch(e){setError(e.message)}finally{setBusy(false)}}}><fieldset disabled={busy}>{o.buyerComparison&&o.buyerComparison.quantity!==o.qty&&<p className="notice">This reference needs reconfirmation for the current quantity. It is excluded from savings until you confirm it again.</p>}<div className="form-grid"><label className="field"><span>Alternative landed price / unit (₹)</span><input name="unitPrice" type="number" min="1" max="1000000" step="0.01" defaultValue={o.buyerComparison?.unitPrice/100||''} required/></label><label className="field"><span>Comparison basis</span><select name="basis" defaultValue={o.buyerComparison?.basis||'Supplier quote'}><option>Supplier quote</option><option>Recent purchase</option></select></label></div><label className="checkbox"><input type="checkbox" name="comparable" required/><span>I am comparing equivalent goods, condition, quantity and included charges.</span></label><p className="subtle">Your order total: {money(o.cost.total)} · {o.qty} units. Savings appear in the total after delivery is confirmed.</p><div className="row-actions"><button className="button primary" type="submit">{busy?'Saving…':'Save comparison'}</button>{o.buyerComparison&&<button className="button secondary" type="button" onClick={async()=>{setBusy(true);setError('');try{await command({type:'order.comparison',id:o.id,clear:true});setSaved(false)}catch(e){setError(e.message)}finally{setBusy(false)}}}>Remove comparison</button>}<button className="button quiet" type="button" onClick={()=>nav('/orders/'+o.id)}>View order</button></div></fieldset></form>}{error&&<p className="error" role="alert">{error}</p>}{saved&&<p className="success" role="status">Comparison saved. Only you and operations can see it.</p>}</>}</details>
}
export default function BusinessDashboard({data,nav,command}){
 const{lang}=useLanguage(),m=businessMetrics(data),seller=data.me.role==='seller',titleFor=o=>o.title||data.lots.find(l=>l.id===o.ref)?.title||'Recovery order',ownQuoteRequests=data.rfqs.filter(r=>r.owner===data.me.id&&r.status==='open'&&r.quotes.length),maxWeek=Math.max(1,...m.weeks.map(w=>w.value)),maxStage=Math.max(1,...m.pipeline.map(p=>p.value));
 return <div className="business-dashboard"><div className="page-heading"><div><h1>{seller?'Your business at a glance.':'Buying and supplying, in one view.'}</h1><p>{seller?'Recover value from surplus. Keep your next purchase in view.':'Track what you buy, what you earn and what needs attention.'}</p></div><div className="row-actions">{seller?<button className="button primary" onClick={()=>nav('/inventory/new')}><Plus size={17}/>Add stock</button>:data.me.capabilities?.buy?<button className="button primary" onClick={()=>nav('/market')}><ShoppingBag size={17}/>Buy surplus</button>:<button className="button primary" onClick={()=>nav('/source')}>Supply fresh stock</button>}</div></div>
 <p className="dashboard-period">All available records · Updated with your orders</p>
 <dl className="business-metrics">{seller?<><Metric label="Cash recovered" value={money(m.cashRecovered)} note="From completed recovery settlements"/><Metric label="Recovery orders" value={m.recovery.length} note="All recovery orders, excluding cancellations"/><Metric label="Payout pending" value={money(m.pendingPayout)} note="Paid orders, still awaiting completion"/><Metric label="Source negotiation savings" value={m.sourceSavingsCount?money(m.sourceSavings):'—'} note={m.sourceSavingsCount?'Against the first offer for the same quantity':'No comparable completed negotiation yet'}/></>:<><Metric label="Surplus purchases" value={money(m.purchaseSpend)} note="Paid goods, premium and delivery; refunds reflected"/><Metric label="Source earnings" value={money(m.supplyEarned)} note="Net payouts from completed supply orders"/><Metric label="Supply payout pending" value={money(m.pendingPayout)} note="Paid supply orders, still awaiting completion"/><Metric label="Estimated purchase savings" value={m.comparisonCount?money(m.purchaseSavings):'—'} note={m.comparisonCount?'Against your like-for-like landed-price references':'Add a comparison to estimate savings'}/></>}</dl>
 <div className="business-main-grid"><section className="business-panel action-board"><div className="section-title"><h2>Needs your attention</h2><span className="task-count">{m.tasks.length+ownQuoteRequests.length}</span></div><p className="muted">Only actions your account can complete.</p>{!m.tasks.length&&!ownQuoteRequests.length?<div className="dashboard-empty"><Package size={28}/><h3>You are up to date.</h3><p>Meesho and your trading partners handle the stages assigned to them.</p></div>:<div className="dashboard-tasks">{m.tasks.slice(0,4).map(x=><button key={x.order.id} onClick={()=>nav('/orders/'+x.order.id)}><span><b>{titleFor(x.order)}</b><small>{x.title}</small></span><span className="task-cta">{x.action}<ArrowRight size={16}/></span></button>)}{ownQuoteRequests.slice(0,2).map(r=><button key={r.id} onClick={()=>nav('/source/'+r.id)}><span><b>{r.title}</b><small>Supplier quotes received</small></span><span className="task-cta">Review quotes<ArrowRight size={16}/></span></button>)}{m.tasks.length>4&&<button className="more-tasks" onClick={()=>nav('/orders')}>View all orders<ArrowRight size={16}/></button>}</div>}</section>
 <section className="business-panel"><h2>Orders in progress</h2><p className="muted">{m.active.length} active orders · buyer and supplier sides</p><div className="pipeline-bars">{m.pipeline.map((p,i)=><div key={p.label}><span>{p.label}</span><div className={'pipeline-track phase-'+i}><i style={{width:(p.value/maxStage*100)+'%'}}/></div><b>{p.value}</b></div>)}</div><button className="text-link" onClick={()=>nav('/orders')}>View orders<ArrowRight size={15}/></button></section></div>
 <div className="business-main-grid secondary-board"><section className="business-panel"><h2>{seller?'Recovery over time':'Supply earnings over time'}</h2><p className="muted">Net settlements · last 6 weeks</p><div className="earnings-bars" role="list" aria-label="Weekly net settlement amounts">{m.weeks.map(w=><div key={w.from} role="listitem"><span>{money(w.value)}</span><div className="earnings-track"><i style={{height:(w.value/maxWeek*100)+'%'}}/></div><small>{new Date(w.from).toLocaleDateString(lang==='hi'?'hi-IN':'en-IN',{day:'numeric',month:'short'})}</small></div>)}</div><details className="metric-method"><summary>How these numbers are calculated</summary><p>Completed settlements count as earnings. Pending payouts are separate. Cancelled orders are excluded. Recovery value is cash received from stock, not assumed profit or savings.</p><p>Only settlements with a recorded date appear in the chart. All values in demo workspaces are illustrative.</p></details></section>
 <section className="business-panel business-ledger"><h2>{seller?'Stock and sourcing':'Your trading overview'}</h2><dl>{seller?<><div><dt>Active stock listings</dt><dd>{m.activeListings}</dd></div><div><dt>Drafts to finish</dt><dd>{m.drafts}</dd></div><div><dt>Units recovered</dt><dd>{m.unitsRecovered}</dd></div><div><dt>Fresh-stock orders</dt><dd>{m.source.length}</dd></div></>:<><div><dt>Surplus purchase orders</dt><dd>{m.recovery.length}</dd></div><div><dt>Fresh-stock supply orders</dt><dd>{m.source.length}</dd></div><div><dt>Completed supply orders</dt><dd>{m.settled.length}</dd></div><div><dt>Purchases with a savings reference</dt><dd>{m.comparisonCount} / {m.eligibleComparisons}</dd></div></>}</dl>{seller?<><p className="subtle">Negotiation savings compare the first supplier offer with the final goods price for the same quantity, on completed orders. They exclude delivery and are separate from recovery earnings.</p><div className="row-actions"><button className="button secondary" onClick={()=>nav('/inventory')}>My stock</button><button className="button secondary" onClick={()=>nav('/source')}>Source fresh stock</button></div></>:<><p className="subtle">Savings use your reference price less your full purchase cost. Missing comparisons are excluded; a negative value means the order cost more.</p><ComparisonEditor orders={m.purchases.filter(o=>o.kind==='recovery')} titleFor={titleFor} nav={nav} command={command}/><button className="text-link" onClick={()=>nav('/source')}>Supply fresh stock<ArrowRight size={15}/></button></>}</section></div>
 <section className="business-panel order-board"><div className="section-title"><h2>Follow your active orders</h2><button className="text-link" onClick={()=>nav('/orders')}>All orders<ArrowRight size={15}/></button></div>{!m.active.length?<p className="muted">No active orders. Your next trade will appear here.</p>:<div className="dashboard-order-list">{m.active.slice().sort((a,b)=>b.createdAt-a.createdAt).slice(0,5).map(o=>{const s=nextStep(o,data.me);return <button key={o.id} onClick={()=>nav('/orders/'+o.id)}><span><b>{titleFor(o)}</b><small>{o.kind==='recovery'?'ReLoop':'Source'} · {o.id.slice(0,6).toUpperCase()}</small></span><span>{s.title}<small>Next: <span>{s.owner}</span></small></span><ArrowRight size={17}/></button>})}</div>}</section>
 </div>
}
