export default {
  "Save": "सेव करें",
  "Saving…": "सेव हो रहा है…",
  "Retry": "फिर कोशिश करें",
  "Draft": "ड्राफ़्ट",
  "Published": "लिस्ट किया गया",
  "Withdrawn": "वापस लिया गया",
  "Gathering stock": "स्टॉक इकट्ठा हो रहा है",
  "Open for bids": "बोली के लिए खुला",
  "Buyer selected": "खरीदार चुना गया",
  "Awaiting payment": "भुगतान का इंतज़ार",
  "Arrange pickup": "पिकअप तय करें",
  "Review inspection": "जाँच की समीक्षा करें",
  "Ready to dispatch": "भेजने के लिए तैयार",
  "Preparing order": "ऑर्डर तैयार हो रहा है",
  "On the way": "रास्ते में है",
  "Delivered": "डिलीवर हो गया",
  "Settled": "भुगतान निपटाया गया",
  "Cancelled": "रद्द किया गया",
  "Order placed": "ऑर्डर किया गया",
  "My stock": "मेरा स्टॉक",
  "Find stock": "स्टॉक खोजें",
  "Orders": "ऑर्डर",
  "Source": "नया स्टॉक",
  "Operations": "संचालन",
  "Activity": "गतिविधि",
  "Seller": "विक्रेता",
  "Buyer": "खरीदार",
  "Supplier": "सप्लायर",
  "seller": "विक्रेता",
  "buyer": "खरीदार",
  "supplier": "सप्लायर",
  "ops": "संचालन",
  "Wholesale buyer": "थोक खरीदार",
  "Fresh-stock supplier": "नए स्टॉक का सप्लायर",
  "Meesho seller": "मीशो विक्रेता",
  "Meesho operations": "मीशो संचालन",
  "Meesho operations · demo": "मीशो संचालन · डेमो",
  "workspace": "कार्यक्षेत्र",
  "Workspace": "कार्यक्षेत्र",
  "Team feedback": "टीम की राय",
  "Proposed Meesho extension": "मीशो में प्रस्तावित सुविधा",
  "Payments and logistics in test mode": "भुगतान और डिलीवरी टेस्ट मोड में हैं",
  "Switch demo view": "डेमो का रोल बदलें",
  "Explore demo": "डेमो देखें",
  "Change language": "भाषा बदलें",
  "Refresh records": "रिकॉर्ड ताज़ा करें",
  "Sign out": "साइन आउट करें",
  "Skip to content": "मुख्य सामग्री पर जाएँ",
  "Main navigation": "मुख्य नेविगेशन",
  "Mobile navigation": "मोबाइल नेविगेशन",
  "Close navigation": "मेन्यू बंद करें",
  "Open navigation": "मेन्यू खोलें",
  "Dismiss error": "संदेश हटाएँ",
  "Meesho concept demo": "मीशो कॉन्सेप्ट डेमो",
  "view · illustrative data": "व्यू · उदाहरण के आँकड़े",
  "Only your demo changes here.": "यहाँ बदलाव केवल आपके डेमो में होंगे।",
  "Opening your workspace…": "आपका कार्यक्षेत्र खुल रहा है…",
  "Inside the seller panel": "विक्रेता पैनल के अंदर",
  "New buyer onboarding": "नए खरीदार का प्रवेश",
  "Supplier network": "सप्लायर नेटवर्क",
  "Inside the operations console": "संचालन पैनल के अंदर",
  "Recover value from leftover stock, then source fresh inventory.": "बचे स्टॉक से पैसे वापस पाएँ, फिर नया स्टॉक मँगाएँ।",
  "Find recovery lots, check a bid budget and buy in bulk.": "बचे स्टॉक के लॉट खोजें, बोली का बजट जाँचें और थोक में खरीदें।",
  "Respond to sourcing requests with a price and dispatch window.": "स्टॉक की ज़रूरत पर कीमत और भेजने की तारीख का ऑफ़र दें।",
  "Resolve holds, inspect stock and release test settlements.": "रुके मामले सुलझाएँ, स्टॉक जाँचें और टेस्ट भुगतान जारी करें।",
  "One extension.": "एक नई सुविधा।",
  "Four sides of the journey.": "एक सफ़र के चार रोल।",
  "ReLoop + Source is our proposed addition to Meesho. Seller and operations views belong within Meesho’s existing software; wholesale buyers and suppliers join the network through their own views.": "ReLoop + Source मीशो में हमारा प्रस्तावित विस्तार है। विक्रेता और संचालन के व्यू मीशो के मौजूदा सॉफ़्टवेयर में होंगे; थोक खरीदार और सप्लायर अपने व्यू से जुड़ेंगे।",
  "No ID or password needed for these demo views.": "डेमो के लिए आईडी या पासवर्ड की ज़रूरत नहीं है।",
  "Try the same journey from each side. Your demo changes are isolated from other visitors and saved for up to 24 hours in this browser. Data and sample images are illustrative; payments and delivery are test events.": "एक ही सफ़र को हर रोल से देखें। आपके बदलाव दूसरे लोगों से अलग हैं और इस ब्राउज़र में 24 घंटे तक रहते हैं। आँकड़े और फ़ोटो उदाहरण हैं; भुगतान और डिलीवरी टेस्ट हैं।",
  "DICE concept demo · not an official Meesho service or live integration.": "DICE कॉन्सेप्ट डेमो · यह मीशो की आधिकारिक या जुड़ी हुई लाइव सेवा नहीं है।",
  "Enter demo": "डेमो खोलें",
  "Opening…": "खुल रहा है…",
  "Continue this view": "इसी व्यू में जाएँ",
  "Back to my workspace": "मेरे कार्यक्षेत्र पर लौटें",
  "I have a saved account — sign in": "मेरा खाता है — साइन इन करें",
  "Close demo chooser": "रोल चुनने का बॉक्स बंद करें",
  "Good stock.": "अच्छा स्टॉक।",
  "A fresh start.": "एक नई शुरुआत।",
  "Find a buyer for leftover inventory, or find the stock your business needs next.": "बचे स्टॉक के लिए खरीदार खोजें या कारोबार के लिए नया स्टॉक मँगाएँ।",
  "Your stock stays with you until a buyer pays.": "खरीदार के भुगतान तक स्टॉक आपके पास रहेगा।",
  "Photos, prices and decisions stay together.": "फ़ोटो, कीमत और सभी फ़ैसले एक जगह रहें।",
  "Proposed Meesho extension · DICE concept demo, not a live integration": "मीशो में प्रस्तावित सुविधा · DICE कॉन्सेप्ट डेमो, लाइव इंटीग्रेशन नहीं",
  "Explore the four demo views": "चारों डेमो रोल देखें",
  "Keep this safe": "इसे सुरक्षित रखें",
  "Your recovery code": "खाता वापस पाने का कोड",
  "This is the only time we display it. You can use it to reset your password without email.": "यह कोड सिर्फ़ अभी दिखेगा। इससे बिना ईमेल के पासवर्ड बदला जा सकता है।",
  "Save recovery code": "रिकवरी कोड सेव करें",
  "I saved it — open my workspace": "मैंने सेव कर लिया — कार्यक्षेत्र खोलें",
  "Sign in": "साइन इन करें",
  "Create account": "खाता बनाएँ",
  "Reset password": "पासवर्ड बदलें",
  "Your business, connected.": "आपका कारोबार, अब जुड़ा हुआ।",
  "Get back to your work.": "अपने काम पर वापस आएँ।",
  "Welcome back.": "फिर से स्वागत है।",
  "Create a workspace for your business.": "अपने कारोबार का कार्यक्षेत्र बनाएँ।",
  "Pick up where you left off, on any device.": "किसी भी डिवाइस पर वहीं से शुरू करें जहाँ छोड़ा था।",
  "I want to": "मैं चाहता हूँ",
  "Sell leftover stock and source new stock": "बचा स्टॉक बेचूँ और नया स्टॉक मँगाऊँ",
  "Buy recovery lots": "बचे स्टॉक के लॉट खरीदूँ",
  "Supply fresh stock": "नए स्टॉक की सप्लाई करूँ",
  "Business name": "कारोबार का नाम",
  "City": "शहर",
  "Username": "यूज़रनेम",
  "Recovery code": "रिकवरी कोड",
  "New password": "नया पासवर्ड",
  "Password": "पासवर्ड",
  "Use at least 12 characters.": "कम-से-कम 12 अक्षर रखें।",
  "Use a recovery code": "रिकवरी कोड से खाता खोलें",
  "Judge-ready test environment. Accounts and stock are saved; payments and courier events use test mode.": "प्रस्तुति के लिए टेस्ट ऐप। खाते और स्टॉक सेव होते हैं; भुगतान और कूरियर की घटनाएँ टेस्ट मोड में हैं।",
  "e.g. aarohi_retail": "जैसे aarohi_retail",
  "Draft not found": "ड्राफ़्ट नहीं मिला",
  "Only your drafts can be edited.": "आप केवल अपने ड्राफ़्ट बदल सकते हैं।",
  "Minimum recovery": "न्यूनतम मिलने वाली रकम",
  "Lot not found": "लॉट नहीं मिला",
  "Refresh the workspace to see the latest stock.": "नया स्टॉक देखने के लिए रिकॉर्ड ताज़ा करें।",
  "All recovery lots": "सभी बचे स्टॉक के लॉट",
  "Know what you’re buying.": "खरीदने से पहले सामान को जानें।",
  "Seller-declared condition": "विक्रेता के अनुसार हालत",
  "Available quantity": "उपलब्ध संख्या",
  "Minimum lot size": "लॉट की न्यूनतम संख्या",
  "Contributions": "शामिल स्टॉक",
  "seller listings": "विक्रेताओं की लिस्टिंग",
  "Photos support a buying decision; they cannot verify hidden damage. Physical inspection comes before dispatch.": "फ़ोटो खरीदने में मदद करती हैं, छिपी खराबी की पुष्टि नहीं करतीं। भेजने से पहले सामान की जाँच होगी।",
  "One compatible lot, traceable contributions.": "एक जैसे सामान का लॉट, हर विक्रेता का साफ़ हिसाब।",
  "Your stock": "आपका स्टॉक",
  "Declared details:": "बताई गई जानकारी:",
  "Contributions join only when the product title, category, condition, city and minimum lot size match. Similar-looking products are not automatically combined.": "सामान का नाम, श्रेणी, हालत, शहर और न्यूनतम लॉट आकार मिलने पर ही स्टॉक जुड़ेगा। केवल मिलता-जुलता दिखने वाला सामान नहीं जोड़ा जाएगा।",
  "Withdraw my uncommitted stock": "बिना बोली वाला मेरा स्टॉक वापस लें",
  "Highest bid / unit": "सबसे ऊँची बोली / नग",
  "Minimum bid / unit": "न्यूनतम बोली / नग",
  "Your stock stays with you. Pickup becomes available after the buyer pays.": "स्टॉक आपके पास रहेगा। खरीदार के भुगतान के बाद पिकअप चुन सकेंगे।",
  "Close auction & award highest bid": "नीलामी बंद करें और सबसे ऊँची बोली चुनें",
  "Open order": "ऑर्डर खोलें",
  "Quantity changes require explicit buyer and seller acceptance.": "संख्या बदलने पर खरीदार और विक्रेता, दोनों की मंज़ूरी ज़रूरी है।",
  "Every handoff, in one place.": "ऑर्डर का हर कदम, एक जगह।",
  "Track payment, inspection, delivery and settlement.": "भुगतान, जाँच, डिलीवरी और पैसे मिलने की स्थिति देखें।",
  "Your orders will appear here.": "आपके ऑर्डर यहाँ दिखेंगे।",
  "A winning recovery bid or accepted supplier quote starts an order.": "बोली जीतने या सप्लायर का ऑफ़र मंज़ूर होने पर ऑर्डर बनता है।",
  "Fresh stock": "नया स्टॉक",
  "Recovery": "बचा स्टॉक",
  "Order not found": "ऑर्डर नहीं मिला",
  "This account may not be part of this order.": "शायद यह खाता इस ऑर्डर से जुड़ा नहीं है।",
  "units": "नग",
  "units ·": "नग ·",
  "units ×": "नग ×",
  "unit": "नग",
  "/ unit": "/ नग",
  "/ unit minimum": "/ नग न्यूनतम",
  "· minimum": "· न्यूनतम",
  "quotes": "ऑफ़र",
  "· needed by": "· चाहिए तारीख तक",
  "All requests": "सभी ज़रूरतें",
  "Request not found": "ज़रूरत नहीं मिली",
  "Refresh to see the latest requests.": "नई ज़रूरतें देखने के लिए रिकॉर्ड ताज़ा करें।",
  "Your quote": "आपका ऑफ़र",
  "Dispatch": "भेजना",
  "Goods": "सामान",
  "Quotes include a price and dispatch window.": "ऑफ़र में कीमत और भेजने की तारीख शामिल होगी।",
  "Send a clear offer.": "पूरी जानकारी के साथ ऑफ़र दें।",
  "Submit quote": "ऑफ़र भेजें",
  "Price / unit (₹)": "कीमत / नग (₹)",
  "Dispatch from": "इस तारीख से भेज सकते हैं",
  "Dispatch by": "इस तारीख तक भेज देंगे",
  "Material, pack details and terms": "सामग्री, पैकिंग और शर्तें",
  "Before you commit.": "ऑर्डर से पहले जाँचें।",
  "Compare the specification and dispatch window. The full test checkout will show the goods amount, service premium and delivery assumption.": "सामान की जानकारी और भेजने की तारीख की तुलना करें। टेस्ट भुगतान में सामान, सेवा शुल्क और अनुमानित डिलीवरी लागत दिखेगी।",
  "View order": "ऑर्डर देखें",
  "Operations access required": "संचालन की अनुमति चाहिए",
  "This page was not found.": "यह पेज नहीं मिला।",
  "No actions yet.": "अभी कोई गतिविधि नहीं है।",
  "Your saved decisions will appear here.": "आपके सेव किए गए फ़ैसले यहाँ दिखेंगे।",
  "Product value": "सामान की कीमत",
  "Service premium (12.5%)": "सेवा शुल्क (12.5%)",
  "Delivery assumption": "अनुमानित डिलीवरी",
  "Total test amount": "कुल टेस्ट रकम",
  "Place my bid": "मेरी बोली लगाएँ",
  "Your bid / unit (₹)": "आपकी बोली / नग (₹)",
  "₹0 listing fee": "₹0 लिस्टिंग शुल्क",
  "That exact photo is already attached. Add another view.": "यह फ़ोटो पहले से जुड़ी है। किसी दूसरे कोण की फ़ोटो जोड़ें।",
  "This looks similar to another view. Make sure it shows different evidence.": "यह फ़ोटो दूसरी जैसी लगती है। सामान का अलग हिस्सा दिखाएँ।",
  "This order was cancelled. Review the inspection history, then correct the quantity, condition and defect details before saving and publishing again.": "यह ऑर्डर रद्द हुआ था। जाँच का रिकॉर्ड देखकर संख्या, हालत और खराबी की जानकारी सही करें; फिर सेव और लिस्ट करें।",
  "Bags": "बैग",
  "Clothing": "कपड़े",
  "Home": "घर का सामान",
  "Kitchen": "रसोई का सामान",
  "Footwear": "जूते-चप्पल",
  "Accessories": "एक्सेसरीज़",
  "Other": "अन्य",
  "Unused surplus": "बिना इस्तेमाल का बचा स्टॉक",
  "Minor visible wear": "हल्के दिखाई देने वाले निशान",
  "Repair required": "मरम्मत ज़रूरी",
  "Category": "श्रेणी",
  "State / UT": "राज्य / केंद्र शासित प्रदेश",
  "All states": "सभी राज्य",
  "Any category": "कोई भी श्रेणी",
  "Any city": "कोई भी शहर",
  "At least (units)": "कम-से-कम संख्या",
  "Unused stock only": "सिर्फ़ बिना इस्तेमाल का स्टॉक",
  "Sample product photo": "उदाहरण की उत्पाद फ़ोटो",
  "Generated sample photos; inspect actual stock before buying.": "ये उदाहरण के लिए बनाई गई फ़ोटो हैं; खरीदने से पहले असली स्टॉक जाँचें।",
  "Find a match…": "मिलता-जुलता सामान खोजें…",
  "Finding the closest stock…": "सबसे मिलता-जुलता स्टॉक खोज रहे हैं…",
  "Preparing your search…": "आपकी खोज तैयार हो रही है…",
  "Preparing photo search…": "फ़ोटो से खोज तैयार हो रही है…",
  "Searching your selected stock…": "चुने हुए स्टॉक में खोज रहे हैं…",
  "This may take a moment the first time.": "पहली बार थोड़ा समय लग सकता है।",
  "How matching helps": "खोज कैसे मदद करती है",
  "Describe what you need in Hindi or English, or use a product photo. Results stay within your category, state, city, condition and quantity filters. A match is a suggestion; check the listing and actual condition before buying.": "हिंदी या अंग्रेज़ी में ज़रूरत लिखें, या सामान की फ़ोटो चुनें। नतीजे आपकी श्रेणी, राज्य, शहर, हालत और संख्या के फ़िल्टर में रहेंगे। नतीजा एक सुझाव है; खरीदने से पहले लिस्टिंग और असली हालत जाँचें।",
  "Use basic text search": "साधारण शब्दों से खोजें",
  "Basic text search is active.": "साधारण शब्दों से खोज चालू है।",
  "No lots meet these filters. Adjust them before matching.": "इन फ़िल्टर में कोई लॉट नहीं है। खोजने से पहले फ़िल्टर बदलें।",
  "Describe the stock you want first.": "पहले बताएँ कि कैसा स्टॉक चाहिए।",
  "Matching…": "खोज रहे हैं…",
  "Matching could not finish. Please try again or type a simpler search.": "खोज पूरी नहीं हुई। फिर कोशिश करें या कम शब्दों में लिखें।",
  "Matched by meaning across languages. All results still meet your filters.": "आपकी ज़रूरत के मतलब से नतीजे मिले हैं। सभी नतीजे आपके फ़िल्टर में हैं।",
  "Matched your photo to stock descriptions. Photo similarity does not verify condition.": "फ़ोटो से मिलता-जुलता स्टॉक मिला है। फ़ोटो की समानता हालत की पुष्टि नहीं करती।",
  "Review the recognised words, then select Match by meaning.": "पहचाने गए शब्द जाँचें, फिर ‘मतलब से खोजें’ चुनें।",
  "Ranking eligible stock…": "मिलता-जुलता स्टॉक क्रम में लगा रहे हैं…",
  "Comparing eligible stock": "चुने हुए स्टॉक की तुलना",
  "outside your filters": "आपके फ़िल्टर से बाहर",
  "Ranked by similarity · selected filters met": "समानता के अनुसार क्रम · आपके फ़िल्टर से मेल",
  "Meets your selected filters": "आपके चुने फ़िल्टर से मेल",
  "No stock fits these filters yet.": "अभी इन फ़िल्टर में स्टॉक नहीं मिला।",
  "The marketplace is ready for its first stock.": "यहाँ पहला स्टॉक लिस्ट होने का इंतज़ार है।",
  "Try another city, quantity or description.": "कोई दूसरा शहर, संख्या या जानकारी आज़माएँ।",
  "Published seller stock will appear here, with its actual photos and minimum price.": "लिस्ट किया गया स्टॉक यहाँ असली फ़ोटो और न्यूनतम कीमत के साथ दिखेगा।",
  "Search stock": "स्टॉक खोजें",
  "Clear search": "खोज मिटाएँ",
  "Speak to search": "बोलकर खोजें",
  "Hindi, English or Hinglish": "हिंदी, अंग्रेज़ी या हिंग्लिश",
  "Done speaking": "बोलना पूरा हुआ",
  "Done": "हो गया",
  "Opening mic…": "माइक खुल रहा है…",
  "Transcribing…": "आपकी बात लिख रहे हैं…",
  "Cancel voice search": "आवाज़ से खोज रद्द करें",
  "Allow the microphone to start speaking.": "बोलने के लिए माइक की अनुमति दें।",
  "Listening… speak naturally, then pause.": "सुन रहे हैं… आराम से बोलें, फिर रुकें।",
  "Turning your words into a search…": "आपकी बात से खोज तैयार हो रही है…",
  "Words added. Check or edit them, then search.": "शब्द जुड़ गए। जाँचें या बदलें, फिर खोजें।",
  "Audio privacy": "आवाज़ की गोपनीयता",
  "Your short recording is processed to turn speech into text. This app does not save the audio.": "आपकी छोटी रिकॉर्डिंग को शब्दों में बदला जाता है। यह ऐप आवाज़ सेव नहीं करता।",
  "Voice search could not connect. Please try again.": "आवाज़ से खोज नहीं जुड़ी। फिर कोशिश करें।",
  "I couldn’t hear a search. Please try again.": "आपकी बात सुनाई नहीं दी। फिर कोशिश करें।",
  "Voice search took too long. Please try again.": "आवाज़ से खोज में समय लग गया। फिर कोशिश करें।",
  "Microphone permission is off. Allow it for this site, then tap the mic again.": "माइक की अनुमति बंद है। इस साइट के लिए अनुमति दें, फिर माइक दबाएँ।",
  "No microphone was found. Connect one or type your search.": "माइक नहीं मिला। माइक जोड़ें या लिखकर खोजें।",
  "Recording stopped unexpectedly. Tap the mic to try again.": "रिकॉर्डिंग रुक गई। फिर कोशिश करने के लिए माइक दबाएँ।",
  "I didn’t hear anything. Check your mic and try again.": "कुछ सुनाई नहीं दिया। माइक जाँचें और फिर कोशिश करें।",
  "I couldn’t hear that clearly. Move closer to the mic and try again.": "आवाज़ साफ़ नहीं आई। माइक के पास आकर फिर कोशिश करें।",
  "This browser cannot record audio. Open this page in Chrome or Safari, or type your search.": "इस ब्राउज़र में रिकॉर्डिंग नहीं हो पा रही। Chrome या Safari में खोलें, या लिखकर खोजें।",
  "Your stock, ready for what’s next.": "आपके स्टॉक का अगला कदम।",
  "List it for free. Keep it with you until a buyer pays.": "मुफ़्त में लिस्ट करें। खरीदार के भुगतान तक सामान आपके पास रहेगा।",
  "Add stock": "स्टॉक जोड़ें",
  "Drafts to finish": "अधूरे ड्राफ़्ट",
  "Published listings": "लिस्ट किया स्टॉक",
  "Seller listing fee": "लिस्टिंग शुल्क",
  "Give leftover stock another chance.": "बचे स्टॉक को एक और मौका दें।",
  "Add your first stock": "पहला स्टॉक जोड़ें",
  "Start with three photos, the quantity and the minimum you want per unit.": "तीन फ़ोटो, संख्या और हर सामान की न्यूनतम कीमत जोड़ें।",
  "Review returned stock": "वापस आए स्टॉक की जाँच करें",
  "Edit draft": "ड्राफ़्ट बदलें",
  "Publish stock": "स्टॉक लिस्ट करें",
  "View my lot": "मेरा लॉट देखें",
  "Tell suppliers what you need.": "सप्लायर को अपनी ज़रूरत बताएँ।",
  "Compare clear quotes before you commit.": "ऑर्डर से पहले कीमत और समय की तुलना करें।",
  "Publish request": "ज़रूरत पोस्ट करें",
  "Product": "सामान",
  "Quantity": "संख्या",
  "Specification, size and material": "माप, कपड़ा और पूरी जानकारी",
  "Delivery city": "डिलीवरी शहर",
  "Needed by": "कब तक चाहिए",
  "One request. Clear prices, quantities and dispatch dates.": "एक ज़रूरत। साफ़ कीमत, संख्या और भेजने की तारीख।",
  "Request stock": "स्टॉक की ज़रूरत बताएँ",
  "No stock requests yet.": "अभी कोई ज़रूरत पोस्ट नहीं है।",
  "What is needed": "सामान की जानकारी",
  "Supplier quotes": "सप्लायर के ऑफ़र",
  "Accept this quote": "यह ऑफ़र मंज़ूर करें",
  "Waiting for supplier quotes.": "सप्लायर के ऑफ़र का इंतज़ार है।",
  "Give buyers a clear picture.": "खरीदार को सामान साफ़ दिखाएँ।",
  "Three photos. An honest description. Your minimum price.": "तीन फ़ोटो। सही जानकारी। आपकी न्यूनतम कीमत।",
  "Show the actual stock": "असली सामान दिखाएँ",
  "Front view": "सामने की फ़ोटो",
  "Defect or detail": "खराबी या बारीकी",
  "All units together": "सभी इकाइयाँ साथ",
  "Uploading…": "अपलोड हो रहा है…",
  "Replace photo": "फ़ोटो बदलें",
  "Take or choose a photo": "फ़ोटो लें या चुनें",
  "A local quality check flags dark or repeated photos. It does not certify authenticity or grade damage. Avoid faces and personal documents.": "फ़ोटो की गुणवत्ता की जाँच कम रोशनी या मिलती-जुलती फ़ोटो दिखाती है। इससे सामान की असलियत या खराबी तय नहीं होती।",
  "Save stock draft": "स्टॉक ड्राफ़्ट सेव करें",
  "Please add all three photos.": "कृपया तीनों फ़ोटो जोड़ें।",
  "Product name and variant": "सामान का नाम और प्रकार",
  "Tan crossbody bag · 24 cm": "भूरा स्लिंग बैग · 24 सेमी",
  "Actual condition": "वास्तविक हालत",
  "Describe the stock and every known defect": "सामान और हर ज्ञात खराबी बताएँ",
  "Units you own": "आपके पास संख्या",
  "Minimum price per unit (₹)": "हर इकाई की न्यूनतम कीमत (₹)",
  "Pickup city": "पिकअप शहर",
  "Minimum combined lot size": "समूह की न्यूनतम संख्या",
  "I own this stock and the details are accurate.": "यह सामान मेरा है और जानकारी सही है।",
  "No return claim or compensation decision is pending for this stock.": "इस स्टॉक पर कोई रिटर्न क्लेम या मुआवज़े का निर्णय बाकी नहीं है।",
  "Your minimum stays yours.": "न्यूनतम कीमत आप तय करते हैं।",
  "Compatible stock can form a bigger lot. A valid bid must meet every seller’s minimum price.": "मिलता-जुलता स्टॉक बड़ा समूह बना सकता है। बोली हर विक्रेता की न्यूनतम कीमत से कम नहीं हो सकती।",
  "Keep your stock with you.": "सामान अपने पास रखें।",
  "Pickup starts only after the winning buyer makes the test payment.": "खरीदार के टेस्ट भुगतान के बाद ही पिकअप शुरू होगा।",
  "Find stock that fits your business.": "अपने कारोबार के लिए सही स्टॉक खोजें।",
  "Start with what you need. Keep condition and economics in view.": "अपनी ज़रूरत बताएँ। हालत और लागत का ध्यान रखें।",
  "Try “bags for school books” or “स्कूल के लिए बैग”": "जैसे “स्कूल के लिए बैग”",
  "Match by meaning": "मतलब से खोजें",
  "Search by photo": "फ़ोटो से खोजें",
  "Use your assigned operator account or the isolated operations demo.": "अपना संचालन खाता या अलग संचालन डेमो खोलें।",
  "A record you can return to.": "हर फ़ैसले का रिकॉर्ड, जब चाहें देखें।",
  "Saved actions from the lots, requests and orders available to your account.": "आपके खाते से जुड़े लॉट, ज़रूरतों और ऑर्डर के सेव किए गए काम।",
  "bid": "बोली",
  "bids": "बोलियाँ",
  "full lot of": "पूरा लॉट",
  "minimum": "न्यूनतम",
  "needed by": "चाहिए तारीख तक"
};
