export default {
  "recovery lots": "बचे स्टॉक के लॉट",
  "matching lots": "मिलते-जुलते लॉट",
  "City totals, including locations not mapped (": "शहरों का हिसाब, नक्शे से बाहर की जगहें भी (",
  "Service premium": "सेवा शुल्क",
  "₹8/unit": "₹8/नग",
  "I reviewed the condition, quantity and complete test cost.": "मैंने हालत, संख्या और पूरी टेस्ट लागत जाँच ली है।",
  "Your bid is saved.": "आपकी बोली सेव हो गई है।",
  "Preparing your search… This may take a moment the first time.": "आपकी खोज तैयार हो रही है… पहली बार थोड़ा समय लग सकता है।",
  "Understanding your request and comparing available stock…": "आपकी ज़रूरत के अनुसार उपलब्ध स्टॉक की तुलना हो रही है…",
  "Comparing the photo with eligible stock descriptions…": "फ़ोटो से मिलता-जुलता स्टॉक खोज रहे हैं…",
  "Choose an image smaller than 20 MB.": "20 MB से छोटी फ़ोटो चुनें।",
  "Please complete the required details.": "ज़रूरी जानकारी पूरी भरें।",
  "Check the quantity or amount.": "संख्या या रकम जाँचें।",
  "Your account cannot perform this action.": "आपके खाते से यह काम नहीं किया जा सकता।",
  "This record was not found.": "यह रिकॉर्ड नहीं मिला।",
  "This record belongs to another account.": "यह रिकॉर्ड दूसरे खाते का है।",
  "Choose a valid date, today or later.": "आज या उसके बाद की सही तारीख चुनें।",
  "Choose an action.": "कोई काम चुनें।",
  "Only a draft can be edited.": "केवल ड्राफ़्ट बदला जा सकता है।",
  "This account has reached its 100-listing limit.": "इस खाते की 100 लिस्टिंग की सीमा पूरी हो गई है।",
  "Add three different photos: front, defect or detail, and full stock.": "तीन अलग फ़ोटो जोड़ें: सामने से, खराबी या बारीक जानकारी, और पूरा स्टॉक।",
  "Confirm ownership and resolve any pending return or compensation claim first.": "मालिकाना हक पक्का करें और लंबित वापसी या मुआवज़े का दावा पहले सुलझाएँ।",
  "Only a draft can be published.": "केवल ड्राफ़्ट लिस्ट किया जा सकता है।",
  "Review and save this returned stock draft before publishing again.": "दोबारा लिस्ट करने से पहले वापस आए स्टॉक का ड्राफ़्ट जाँचकर सेव करें।",
  "This stock is not listed.": "यह स्टॉक लिस्ट नहीं है।",
  "A bid or commitment already exists; stock is locked.": "बोली या पक्का ऑर्डर है; स्टॉक अभी वापस नहीं ले सकते।",
  "This lot is not available for your bid.": "इस लॉट पर आपकी बोली नहीं लग सकती।",
  "Your bid must meet every seller’s minimum and exceed the current bid.": "बोली हर विक्रेता की न्यूनतम कीमत से कम न हो और मौजूदा बोली से ज़्यादा हो।",
  "An open lot with at least one bid is required.": "कम-से-कम एक बोली वाला खुला लॉट चाहिए।",
  "This order cannot be paid by this account.": "इस खाते से इस ऑर्डर का भुगतान नहीं हो सकता।",
  "Pickup can only be booked for your paid stock.": "अपने भुगतान किए हुए स्टॉक का ही पिकअप तय कर सकते हैं।",
  "Every seller must book pickup before inspection.": "जाँच से पहले हर विक्रेता पिकअप तय करे।",
  "Enter the accepted quantity for each contribution.": "हर विक्रेता के स्टॉक की मंज़ूर संख्या भरें।",
  "No inspection decision is waiting for you.": "अभी आपकी मंज़ूरी के लिए कोई जाँच नहीं है।",
  "No accepted stock remains; cancel this order.": "कोई मंज़ूर स्टॉक नहीं बचा; ऑर्डर रद्द करें।",
  "Only the buyer or operations can cancel.": "केवल खरीदार या संचालन टीम रद्द कर सकती है।",
  "Raise an issue for an order already in progress.": "आगे बढ़ चुके ऑर्डर के लिए समस्या बताएँ।",
  "All parties must accept inspection first.": "पहले सभी पक्ष जाँच मंज़ूर करें।",
  "This supplier order cannot be dispatched.": "यह सप्लायर ऑर्डर अभी भेजा नहीं जा सकता।",
  "Only the buyer can confirm a shipped order.": "भेजा गया स्टॉक केवल खरीदार मिलने की पुष्टि कर सकता है।",
  "This order belongs to other users.": "यह ऑर्डर दूसरे लोगों का है।",
  "This order cannot receive a delivery issue.": "इस ऑर्डर पर डिलीवरी की समस्या नहीं जोड़ी जा सकती।",
  "There is no open issue.": "कोई खुली समस्या नहीं है।",
  "Confirm delivery and resolve every issue before settlement.": "भुगतान निपटाने से पहले डिलीवरी पक्की करें और सभी समस्याएँ सुलझाएँ।",
  "This request is not open for your quote.": "इस ज़रूरत पर आप अभी ऑफ़र नहीं दे सकते।",
  "The dispatch window must fit the requested date.": "भेजने की तारीख माँगी गई तारीख तक होनी चाहिए।",
  "You have already quoted on this request.": "आप इस ज़रूरत पर पहले ही ऑफ़र दे चुके हैं।",
  "A quote has already been selected.": "ऑफ़र पहले ही चुना जा चुका है।",
  "This action is not supported.": "यह काम अभी उपलब्ध नहीं है।",
  "Stock draft reviewed and updated": "स्टॉक ड्राफ़्ट जाँचकर बदला गया",
  "Stock draft created": "स्टॉक ड्राफ़्ट बना",
  "Stock added to a compatible recovery lot": "स्टॉक एक जैसे सामान के लॉट में जुड़ा",
  "Uncommitted stock withdrawn": "बिना बोली वाला स्टॉक वापस लिया गया",
  "New recovery bid received": "स्टॉक की नई बोली मिली",
  "Auction closed; highest valid bid awarded": "नीलामी बंद; सबसे ऊँची मान्य बोली चुनी गई",
  "Test payment recorded; no money charged": "टेस्ट भुगतान दर्ज हुआ; कोई पैसा नहीं कटा",
  "Seller pickup slot confirmed": "विक्रेता का पिकअप समय तय हुआ",
  "Inspection recorded; buyer and sellers must accept before dispatch": "जाँच दर्ज हुई; भेजने से पहले खरीदार और विक्रेता मंज़ूर करें",
  "Revised inspection explicitly accepted": "बदली हुई जाँच साफ़ तौर पर मंज़ूर हुई",
  "Order cancelled; full test refund recorded and stock released for review": "ऑर्डर रद्द; पूरी टेस्ट वापसी दर्ज हुई और स्टॉक फिर जाँच के लिए खुला",
  "Test dispatch recorded": "टेस्ट डिस्पैच दर्ज हुआ",
  "Buyer confirmed receipt": "खरीदार ने सामान मिलने की पुष्टि की",
  "Issue raised; settlement is on hold": "समस्या दर्ज; भुगतान रोका गया",
  "Operations recorded an issue resolution": "संचालन टीम ने समाधान दर्ज किया",
  "Test settlement recorded; seller receives the cleared product value": "टेस्ट भुगतान दर्ज; विक्रेता को मंज़ूर सामान की रकम मिलेगी"
};
