import React,{useState} from 'react';
import {ArrowRight} from 'lucide-react';
import {sourceStatus} from './SourceWorkspace.jsx';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format((n||0)/100);
export function OpsLots({data,nav}){
 const[query,setQuery]=useState(''),[stage,setStage]=useState('open'),[page,setPage]=useState(0);
 const rows=data.lots.filter(l=>(!stage||l.status===stage)&&[l.id,l.title,l.city,...l.members.map(m=>m.business)].join(' ').toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(rows.length/20)),current=Math.min(page,pages-1);
 return <><div className="page-heading"><div><h1>Lots & auctions</h1><p>Review seller contributions, inspection progress and bids before awarding a lot.</p></div></div><div className="management-filters"><label className="field"><span>Search lots</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Lot ID, product, seller or city"/></label><label className="field"><span>Auction status</span><select value={stage} onChange={e=>{setStage(e.target.value);setPage(0)}}><option value="open">Open for bids</option><option value="forming">Gathering stock</option><option value="awarded">Buyer selected</option><option value="cancelled">Cancelled</option><option value="withdrawn">Withdrawn</option><option value="">All statuses</option></select></label></div><div className="management-table"><table><thead><tr><th>Lot / product</th><th>Seller / pickup city</th><th>Units</th><th>Bids / highest bid</th><th>Inspection / order stage</th><th>Action</th></tr></thead><tbody>{rows.slice(current*20,current*20+20).map(l=>{const o=data.orders.find(o=>o.id===l.orderId);return <tr key={l.id}><td><b>{l.title}</b><small>{l.id.slice(0,8)}</small><span className="badge">{l.status==='open'?'Open for bids':l.status==='awarded'?'Buyer selected':l.status==='forming'?'Gathering stock':l.status==='cancelled'?'Cancelled':'Withdrawn'}</span></td><td>{[...new Set(l.members.map(m=>m.business))].map(x=><div key={x}>{x}</div>)}<small>{l.city}</small></td><td>{l.members.reduce((n,m)=>n+m.qty,0)}</td><td>{l.bidCount}<small>{l.highestBid?money(l.highestBid)+' / unit':'No bids yet'}</small></td><td>{o?o.inspection?'Inspection recorded':o.status==='awaiting_payment'?'Awaiting payment':'Awaiting inspection':'Not yet awarded'}</td><td><button className="button secondary" onClick={()=>nav('/market/'+l.id)}>{l.status==='open'&&l.bidCount?'Review bids & award':'Review lot'}<ArrowRight size={15}/></button></td></tr>})}</tbody></table>{!rows.length&&<p className="empty">No lots match these filters.</p>}</div><div className="table-pagination"><button className="button secondary" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>{current+1} / {pages} · {rows.length} lots</span><button className="button secondary" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next</button></div></>
}
export function OpsProcurement({data,nav}){
 const[query,setQuery]=useState(''),[status,setStatus]=useState('');const rows=data.rfqs.filter(r=>(!status||r.status===status)&&[r.title,r.city,r.business,r.id].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-heading"><div><h1>Procurement oversight</h1><p>Follow seller requests, supplier negotiations and agreed orders.</p></div></div><div className="management-filters"><label className="field"><span>Search requests</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Product, city or seller"/></label><label className="field"><span>Request status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All requests</option><option value="open">Accepting quotes</option><option value="ordered">Order placed</option></select></label></div><div className="management-table"><table><thead><tr><th>Request / seller</th><th>Destination / units</th><th>Status</th><th>Supplier quotes</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.title}</b><small>{r.business} · {r.id.slice(0,8)}</small></td><td>{r.city}<small>{r.qty} units</small></td><td><span className="badge">{sourceStatus(r)}</span></td><td>{r.quotes.length}</td><td><button className="button secondary" onClick={()=>nav('/source/'+r.id)}>Review procurement<ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No requests in this view.</p>}</div></>
}
export function OpsSettlements({data,nav}){
 const[tab,setTab]=useState('issues');const rows=data.orders.filter(o=>tab==='issues'?!!o.issue:tab==='ready'?o.status==='delivered'&&!o.issue:o.status==='settled');
 return <><div className="page-heading"><div><h1>Issues & settlements</h1><p>Resolve the hold before releasing the test settlement.</p></div></div><div className="workspace-tabs"><button aria-pressed={tab==='issues'} onClick={()=>setTab('issues')}>Open issues</button><button aria-pressed={tab==='ready'} onClick={()=>setTab('ready')}>Ready to settle</button><button aria-pressed={tab==='settled'} onClick={()=>setTab('settled')}>Settled history</button></div><div className="management-table"><table><thead><tr><th>Order / product</th><th>Flow</th><th>Issue / stage</th><th>Goods value</th><th>Action</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{o.title||data.lots.find(l=>l.id===o.ref)?.title||'Recovery order'}</b><small>{o.id.slice(0,8)}</small></td><td>{o.kind==='source'?'Fresh stock':'Recovery'}</td><td>{o.issue|| (o.status==='settled'?'Settled':'Ready to settle')}</td><td>{money(o.cost.goods)}</td><td><button className="button secondary" onClick={()=>nav('/orders/'+o.id)}>{o.issue?'Resolve issue':o.status==='settled'?'View order':'Release test settlement'}<ArrowRight size={15}/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No orders in this view.</p>}</div></>
}
