import React,{useState} from 'react';
import {ArrowLeft,ArrowRight,Plus,ShieldCheck,Settings2} from 'lucide-react';
import {categories,catalogCities} from './catalog.mjs';
import {useLanguage} from './i18n.jsx';
import {sourceCost} from './source-pricing.mjs';
import {BillSummary,EarningsSummary} from './FinancialSummary.jsx';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n/100);
const terms=['Standard packing included','Unbranded goods','Assorted sizes as requested','Inspection before dispatch'];
const questions=['Is standard packing included?','Does the material match the request?','Can you supply the requested size mix?'];
const answers=['Yes, confirmed','No, not included','Please review my revised offer'];
const latest=(q,r)=>q.offers?.at(-1)||{revision:0,by:q.owner,side:'supplier',price:q.price,qty:r.qty,dispatchFrom:q.dispatchFrom,dispatchTo:q.dispatchTo,terms:[],at:q.at,expiresAt:Math.min(q.at+7*86400000,Date.parse(r.neededBy)+86400000,Date.parse(q.dispatchTo)+86400000)};
export const sourceStatus=r=>r.status==='ordered'?'Order placed':r.quotes.length?'Quotes received':'Awaiting supplier quotes';
export function RunButton({run,children,secondary=false,...props}){const[busy,setBusy]=useState(false),[error,setError]=useState('');return <><button className={'button '+(secondary?'secondary':'primary')} disabled={busy} {...props} onClick={async()=>{setBusy(true);setError('');try{await run()}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'Saving…':children}</button>{error&&<p className="error" role="alert">{error}</p>}</>}
export function Breakdown({qty,price,view='buyer'}){const c=sourceCost(qty,price);return <>{view!=='supplier'&&<BillSummary value={c} source ops={view==='ops'}/>} {view!=='buyer'&&<EarningsSummary ops={view==='ops'} heading={view==='ops'?'Supplier payout':'Your earnings'} payout={{goods:c.goods,fee:c.supplierFee,net:c.supplierNet,feeRate:4.5,status:'estimated'}}/>}</>}
function OfferForm({r,offer,onSubmit,onCancel,supplier}){
 const[price,setPrice]=useState(offer?offer.price/100:''),[qty,setQty]=useState(offer?.qty||r.qty),[from,setFrom]=useState(offer?.dispatchFrom||''),[to,setTo]=useState(offer?.dispatchTo||''),[selected,setSelected]=useState(offer?.terms||[]),[hours,setHours]=useState(48),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="form offer-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSubmit({price:Math.round(Number(price)*100),qty:Number(qty),dispatchFrom:from,dispatchTo:to,terms:selected,expiresHours:Number(hours)})}catch(e){setError(e.message)}finally{setBusy(false)}}}>
 <h3>{offer?'Make a counteroffer':'Send a clear offer.'}</h3><p className="muted">Only price, quantity, dates and listed terms are shared. Keep the agreement here.</p>
 <fieldset disabled={busy}><div className="form-grid"><label className="field"><span>Price / unit (₹)</span><input type="number" min="1" max="1000000" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label className="field"><span>Quantity offered</span><input type="number" min="1" max="10000" value={qty} onChange={e=>setQty(e.target.value)} required/></label><label className="field"><span>Dispatch from</span><input type="date" value={from} min={new Date().toISOString().slice(0,10)} max={r.neededBy} onChange={e=>setFrom(e.target.value)} required/></label><label className="field"><span>Dispatch by</span><input type="date" value={to} min={from||new Date().toISOString().slice(0,10)} max={r.neededBy} onChange={e=>setTo(e.target.value)} required/></label></div>
 <label className="field"><span>Offer valid for</span><select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={24}>24 hours</option><option value={48}>48 hours</option><option value={72}>72 hours</option></select></label>
 <div className="offer-terms">{terms.map(x=><label key={x}><input type="checkbox" checked={selected.includes(x)} onChange={e=>setSelected(e.target.checked?[...selected,x]:selected.filter(y=>y!==x))}/><span>{x}</span></label>)}</div>
 <Breakdown qty={Number(qty)||0} price={Math.round(Number(price)*100)||0} view={supplier?'supplier':'buyer'}/><p className="subtle">Offer validity also ends at the dispatch deadline.</p>
 {error&&<p className="error" role="alert">{error}</p>}<div className="row-actions"><button className="button primary" type="submit">{busy?'Saving…':offer?'Send counteroffer':'Submit quote'}<ArrowRight size={16}/></button>{onCancel&&<button className="button secondary" type="button" onClick={onCancel}>Cancel</button>}</div></fieldset></form>
}
function Clarifications({q,r,me,command,offer,closed}){
 const[question,setQuestion]=useState(questions[0]);const mine=me.id===r.owner;
 return <details className="clarifications"><summary>Clarify the terms</summary><p className="subtle">Private preset questions and replies. No external contact details.</p>
 {(q.clarifications||[]).filter(c=>!c.questionId).map(c=><div className="clarification-item" key={c.id}><b>{c.code}</b>{(q.clarifications||[]).filter(a=>a.questionId===c.id).map(a=><p key={a.id}>{a.code}</p>)}{!mine&&!closed&&!(q.clarifications||[]).some(a=>a.questionId===c.id)&&<div className="row-actions">{answers.map(code=><RunButton key={code} secondary run={()=>command({type:'quote.clarify',id:r.id,quoteId:q.id,revision:offer.revision,questionId:c.id,code})}>{code}</RunButton>)}</div>}</div>)}
 {mine&&!closed&&<div className="row-actions"><label className="field"><span>Choose a clarification</span><select value={question} onChange={e=>setQuestion(e.target.value)}>{questions.map(x=><option key={x}>{x}</option>)}</select></label><RunButton secondary run={()=>command({type:'quote.clarify',id:r.id,quoteId:q.id,revision:offer.revision,code:question})}>Ask supplier</RunButton></div>}</details>
}
function QuoteCard({q,r,me,index,command,nav}){
 const[edit,setEdit]=useState(false),[review,setReview]=useState(false),{lang}=useLanguage();const o=latest(q,r),mine=me.id===r.owner,isSupplier=me.id===q.owner,ops=me.role==='ops',expired=o.expiresAt<=Date.now(),closed=r.status!=='open'||q.state==='declined'||q.state==='accepted',waiting=o.by===me.id,agreed=q.state==='agreed';
 const send=(type,extra={})=>command({type,id:r.id,quoteId:q.id,revision:o.revision,...extra});
 const status=closed?(q.state==='declined'?'Declined':r.status==='ordered'&&q.state!=='accepted'?'Request closed':'Order placed'):expired?'Offer expired':agreed?'Agreed · ready for checkout':waiting?'Waiting for the other party':'Your response needed';
 return <article className="negotiation-card"><div className="offer-heading"><div><h2>{isSupplier?'Your quote':'Supplier '+(index+1)}</h2><span className={'badge '+(expired?'cancelled':'')}>{ops?(closed?status:'Negotiation in progress'):status}</span></div><div className="offer-price"><strong>{money(o.price)}</strong><span> / unit</span><p>{o.qty} units</p></div></div>
 <p>Dispatch {o.dispatchFrom} — {o.dispatchTo}</p>{o.terms.length>0&&<ul className="term-pills">{o.terms.map(x=><li key={x}>{x}</li>)}</ul>}
 <p className="subtle">Offer expires: {new Date(o.expiresAt).toLocaleString(lang==='hi'?'hi-IN':'en-IN')}</p>
 {(isSupplier||ops)&&!closed&&<Breakdown qty={o.qty} price={o.price} view={ops?'ops':'supplier'}/>}
 <details className="offer-history"><summary>Offer history</summary><ol>{(q.offers||[o]).map((h,historyIndex)=><li key={h.revision}><b>{h.side==='requester'?'Seller counteroffer':'Supplier offer'} · {historyIndex+1}</b><p>{money(h.price)} / unit · {h.qty} units · {h.dispatchFrom} — {h.dispatchTo}</p>{h.terms?.length>0&&<p>{h.terms.map((term,i)=><React.Fragment key={term}>{i>0?' · ':''}<span>{term}</span></React.Fragment>)}</p>}</li>)}</ol></details>
 {!ops&&!closed&&<>
 {!edit&&!review&&<div className="row-actions">
 {mine&&!expired&&(o.side==='supplier'||agreed)&&<button className="button primary" onClick={()=>setReview(true)}>Review & accept</button>}
 {isSupplier&&!expired&&o.side==='requester'&&!agreed&&<RunButton run={()=>send('quote.agree')}>Agree to counteroffer</RunButton>}
 {(!waiting||expired)&&<button className="button secondary" onClick={()=>setEdit(true)}>{expired?'Send a fresh offer':'Make a counteroffer'}</button>}
 {!waiting&&!expired&&<RunButton secondary run={()=>send('quote.decline')}>Decline offer</RunButton>}
 </div>}
 {edit&&<OfferForm key={o.revision} r={r} offer={o} supplier={isSupplier} onCancel={()=>setEdit(false)} onSubmit={async values=>{await send('quote.counter',values);setEdit(false)}}/>}
 {review&&<div className="accept-review"><h3>Review the agreed terms</h3><p>{o.qty} units · {money(o.price)} / unit</p><p>Dispatch {o.dispatchFrom} — {o.dispatchTo}</p><Breakdown qty={o.qty} price={o.price}/><p className="subtle">These terms are locked when the order is created. Payment happens on the next screen.</p><div className="row-actions"><RunButton run={async()=>{const v=await send('quote.accept');nav('/orders/'+v.id)}}>Confirm terms & create order</RunButton><button className="button secondary" onClick={()=>setReview(false)}>Back to negotiation</button></div></div>}
 </>}
 {(mine||isSupplier)&&<Clarifications q={q} r={r} me={me} command={command} offer={o} closed={closed||expired}/>}
 </article>
}
export function SourceDetail({r,me,command,nav}){
 if(!r)return <div className="empty"><h1>Request not available</h1><p>This request is outside your workspace or supply coverage.</p></div>;
 const own=me.id===r.owner,ops=me.role==='ops',canQuote=me.role==='partner'&&me.capabilities?.supply&&r.status==='open'&&!r.quotes.some(q=>q.owner===me.id);
 return <><button className="back" onClick={()=>nav('/source')}><ArrowLeft size={17}/>All requests</button><div className="page-heading"><div><h1>{r.title}</h1><p>{r.qty} units · {r.city} · needed by {r.neededBy}</p></div><span className="badge">{sourceStatus(r)}</span></div><div className="source-detail-grid"><section><div className="section"><h2>What is needed</h2><p>{r.description}</p><p className="muted">{r.business} · {r.city}</p></div><div className="section-title"><h2>{ops?'Procurement offers':'Supplier quotes'}</h2></div>{r.quotes.length?r.quotes.map((q,i)=><QuoteCard key={q.id} q={q} r={r} me={me} index={i} command={command} nav={nav}/>):<div className="empty"><h2>{own?'Waiting for supplier quotes.':'No quote submitted yet.'}</h2><p>{own?'Quotes include a price and dispatch window.':'Send your price and dispatch dates to the seller.'}</p></div>}</section><aside className="buy-panel">{canQuote?<OfferForm r={r} supplier onSubmit={v=>command({type:'quote.submit',id:r.id,...v})}/>:<><ShieldCheck size={24}/><h2>{ops?'Procurement oversight':'Keep the agreement here.'}</h2><p>{ops?'Review requests, offer history and fulfilment. Commercial terms are agreed by the seller and supplier.':'Counteroffers and clarifications stay private between both businesses. Accepted terms are saved with the order.'}</p>{r.orderId&&<button className="button primary" onClick={()=>nav('/orders/'+r.orderId)}>View order<ArrowRight size={16}/></button>}</>}</aside></div></>
}
export function SourceHub({data,nav}){
 const[tab,setTab]=useState('requests'),[query,setQuery]=useState('');const{me}=data,partner=me.role==='partner',ops=me.role==='ops';
 const rows=data.rfqs.filter(r=>!partner||(tab==='quotes'?r.quotes.some(q=>q.owner===me.id):r.status==='open'&&!r.quotes.some(q=>q.owner===me.id))).filter(r=>[r.title,r.city,r.business].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-heading"><div><h1>{ops?'Procurement oversight':partner?'Supply fresh stock':'Source fresh stock'}</h1><p>{ops?'Follow sourcing requests, negotiated terms and fulfilment.':partner?'Requests matched to your categories, delivery coverage and capacity.':'Request what you need. Compare offers and negotiate here.'}</p></div>{me.role==='seller'?<div className="row-actions"><button className="button secondary" onClick={()=>nav('/supply-orders')}>Fresh-stock orders</button> <button className="button primary" onClick={()=>nav('/source/new')}><Plus size={16}/>Request stock</button></div>:partner?<button className="button secondary" onClick={()=>nav('/partner')}><Settings2 size={16}/>Supply preferences</button>:null}</div>
 {partner&&<><div className="capability-note"><b>Supply coverage</b><span>{me.supplyProfile.categories.map((x,i)=><React.Fragment key={x}>{i?' · ':''}<span>{x}</span></React.Fragment>)||'Not set'}</span><span>{me.supplyProfile.states.map((x,i)=><React.Fragment key={x}>{i?', ':''}<span>{x}</span></React.Fragment>)}</span><span>Up to {me.supplyProfile.capacity} units per order</span></div><div className="workspace-tabs"><button aria-pressed={tab==='requests'} onClick={()=>setTab('requests')}>Requests to quote</button><button aria-pressed={tab==='quotes'} onClick={()=>setTab('quotes')}>My quotes</button><button onClick={()=>nav('/supply-orders')}>Supply orders</button></div></>}
 <label className="field search-records"><span>Search requests</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Product, city or seller"/></label>
 {!rows.length?<div className="empty"><h2>No requests in this view.</h2><p>{partner?'Check your supply preferences or return when a matching request arrives.':'Create a stock request to receive supplier offers.'}</p></div>:<div className="record-list">{[...rows].reverse().map(r=><button className="order-row" key={r.id} onClick={()=>nav('/source/'+r.id)}><div className="row-main"><span className="badge">{partner&&r.status==='open'?'Accepting quotes':sourceStatus(r)}</span><h2>{r.title}</h2><p>{r.qty} units · {r.city} · needed by {r.neededBy}</p><small>{r.business}</small></div><span>{partner?r.quotes.some(q=>q.owner===me.id)?'Your quote saved':'Quote opportunity':r.quotes.length+' quotes'}</span><ArrowRight size={18}/></button>)}</div>}</>
}
export function PartnerPreferences({me,command}){
 const p=me.supplyProfile||{categories:[],states:[],capacity:0};const[buy,setBuy]=useState(!!me.capabilities?.buy),[supply,setSupply]=useState(!!me.capabilities?.supply),[cats,setCats]=useState(p.categories),[states,setStates]=useState(p.states),[capacity,setCapacity]=useState(p.capacity||100),[saved,setSaved]=useState(false);
 const toggle=(x,list,set)=>set(list.includes(x)?list.filter(y=>y!==x):[...list,x]);
 return <><div className="page-heading"><div><h1>Business capabilities</h1><p>One account. Choose the work your business can fulfil.</p></div></div><div className="preferences-card"><div className="offer-terms"><label><input type="checkbox" checked={buy} onChange={e=>{setBuy(e.target.checked);setSaved(false)}}/><span>Buy surplus</span></label><label><input type="checkbox" checked={supply} onChange={e=>{setSupply(e.target.checked);setSaved(false)}}/><span>Supply fresh stock</span></label></div>{supply&&<><h2>Product categories</h2><div className="preference-options">{categories.map(x=><label key={x}><input type="checkbox" checked={cats.includes(x)} onChange={()=>{toggle(x,cats,setCats);setSaved(false)}}/><span>{x}</span></label>)}</div><h2>Delivery coverage</h2><div className="preference-options">{[...new Set(catalogCities.map(x=>x.state))].sort().map(x=><label key={x}><input type="checkbox" checked={states.includes(x)} onChange={()=>{toggle(x,states,setStates);setSaved(false)}}/><span>{x}</span></label>)}</div><label className="field"><span>Maximum units per supply order</span><input type="number" min="1" max="10000" value={capacity} onChange={e=>{setCapacity(e.target.value);setSaved(false)}}/></label></>}<RunButton run={async()=>{await command({type:'partner.configure',buy,supply,categories:cats,states,capacity:Number(capacity)});setSaved(true)}}>Save capabilities</RunButton>{saved&&<p className="success" role="status">Capabilities saved. Your requests and actions now follow these settings.</p>}</div></>
}
