import {mkdir,copyFile} from 'node:fs/promises';
import {build} from 'esbuild';
await build({entryPoints:['qr-entry.mjs'],bundle:true,format:'esm',platform:'browser',outfile:'dist/client/qr.js',minify:true});
await mkdir('dist/client/vendor',{recursive:true});
for(const file of ['transformers.min.js','ort-wasm-simd-threaded.jsep.mjs','ort-wasm-simd-threaded.jsep.wasm'])await copyFile('node_modules/@huggingface/transformers/dist/'+file,'dist/client/vendor/'+file);
await copyFile('node_modules/@huggingface/transformers/LICENSE','dist/client/vendor/transformers-LICENSE.txt');
await copyFile('node_modules/qrcode/license','dist/client/vendor/qrcode-LICENSE.txt');
await mkdir('dist/server',{recursive:true});
await copyFile('worker.mjs','dist/server/index.js');
await copyFile('shared-service.mjs','dist/server/shared-service.mjs');
await copyFile('application-service.mjs','dist/server/application-service.mjs');
await copyFile('app-domain.mjs','dist/server/app-domain.mjs');
await copyFile('order-financials.mjs','dist/server/order-financials.mjs');
await copyFile('app-demo.mjs','dist/server/app-demo.mjs');
await copyFile('demo-catalog.mjs','dist/server/demo-catalog.mjs');
await copyFile('demo-expand.mjs','dist/server/demo-expand.mjs');
for(const file of ['demo-personas.mjs','partner-access.mjs','negotiation.mjs'])await copyFile(file,'dist/server/'+file);
await mkdir('dist/.openai',{recursive:true});
await copyFile('.openai/hosting.json','dist/.openai/hosting.json');
console.log('Review assets and comment service prepared.');
