// Canonical values stay in English; the interface translates their labels.
export const categories=['Bags','Clothing','Home','Kitchen','Footwear','Accessories','Other'];
export const catalogProducts=[
['crossbody','Tan crossbody bags','टैन रंग के क्रॉसबॉडी बैग','Bags','Minor visible wear',8500,'Tan faux-leather shoulder handbags, adjustable straps, zipped pockets. Light surface scuffs; straps and zips need inspection.','टैन कृत्रिम चमड़े के शोल्डर बैग, लंबाई बदलने वाला पट्टा और ज़िप की जेब। हल्के निशान हैं; पट्टे और ज़िप की जाँच ज़रूरी है।'],
['backpack','School backpacks · navy','नेवी रंग के स्कूल बैकपैक','Bags','Unused surplus',12000,'Navy school bags for books, padded shoulder straps, two compartments. Unused end-of-season inventory; check zip and seam finish.','किताबों के लिए नेवी स्कूल बैग, गद्देदार पट्टे और दो खाने। सीज़न के बाद बचा अनबिका स्टॉक; ज़िप और सिलाई जाँचें।'],
['tote','Plain cotton tote bags','सादे सूती टोट बैग','Bags','Unused surplus',5500,'Natural cotton shopping tote bags, reinforced long handles, no print. Reusable carry bags for groceries, gifting and retail shops.','बिना प्रिंट के प्राकृतिक सूती शॉपिंग बैग, मज़बूत लंबे हैंडल। किराने, उपहार और दुकानों के लिए दोबारा इस्तेमाल होने वाले बैग।'],
['kurta','Cotton kurtas · mixed sizes','सूती कुर्ते · अलग-अलग साइज़','Clothing','Unused surplus',14500,'Breathable cotton straight kurtas in teal, rose and indigo. Mixed M, L and XL sizes for summer daily wear; size ratio confirmed at inspection.','टील, गुलाबी और इंडिगो रंग के हल्के सूती कुर्ते। गर्मियों के रोज़मर्रा के पहनावे के लिए M, L और XL साइज़; जाँच पर साइज़ का अनुपात तय होगा।'],
['saree','Printed cotton sarees','प्रिंट वाली सूती साड़ियाँ','Clothing','Unused surplus',22000,'Lightweight cotton sarees with small floral block prints and woven borders. Maroon, mustard and indigo assortment for everyday wear.','छोटे फूलों के ब्लॉक प्रिंट और बुने बॉर्डर वाली हल्की सूती साड़ियाँ। रोज़मर्रा के लिए मैरून, सरसों और इंडिगो रंग।'],
['polo','Plain cotton polo T-shirts','सादी सूती पोलो टी-शर्ट','Clothing','Unused surplus',9500,'Unbranded cotton polo t-shirts with collars, navy grey olive and white, mixed adult sizes. Suitable for shop resale or uniform supply.','कॉलर वाली बिना ब्रांड की सूती पोलो टी-शर्ट, नेवी, ग्रे, ऑलिव और सफ़ेद रंग, वयस्कों के अलग-अलग साइज़। दुकान या यूनिफ़ॉर्म की सप्लाई के लिए।'],
['cushion','Cotton cushion covers','सूती कुशन कवर','Home','Unused surplus',6500,'Square cotton cushion covers, ivory and indigo geometric prints, zipped closure, 16-inch size. Covers only; no cushion filling included.','16 इंच के चौकोर सूती कुशन कवर, आइवरी और इंडिगो ज्यामितीय प्रिंट, ज़िप बंद। केवल कवर; अंदर की भराई शामिल नहीं है।'],
['towel','Terry cotton bath towels','टेरी सूती नहाने के तौलिए','Home','Unused surplus',11000,'Absorbent terry cotton bath towels in white, blue and sage. Soft home and guest-house linen; mixed colour wholesale pack.','सफ़ेद, नीले और सेज रंग के पानी सोखने वाले टेरी सूती तौलिए। घर और गेस्ट हाउस के लिए मुलायम तौलिए; मिले-जुले रंग का थोक पैक।'],
['lunchbox','Steel two-tier lunch boxes','स्टील के दो-खाने वाले टिफ़िन','Kitchen','Unused surplus',16000,'Stainless-steel two-tier tiffin lunch boxes, removable lids and locking clasps. Kitchen and school lunch use; inspect closures before dispatch.','स्टेनलेस स्टील के दो-खाने वाले टिफ़िन, अलग होने वाले ढक्कन और लॉकिंग क्लिप। रसोई और स्कूल के लिए; भेजने से पहले क्लिप जाँचें।'],
['mug','Ceramic tea mugs · assorted','सिरेमिक चाय के मग · मिले-जुले रंग','Kitchen','Unused surplus',4500,'Plain ceramic tea and coffee mugs in cream sage and blue, 250 ml. Assorted wholesale cartons; fragile goods require a breakage check and careful packing.','क्रीम, सेज और नीले रंग के 250 मिलीलीटर के सादे सिरेमिक चाय-कॉफ़ी मग। थोक कार्टन; टूट-फूट की जाँच और सावधानी से पैकिंग ज़रूरी है।'],
['sneaker','Canvas casual sneakers','कैनवस के कैज़ुअल स्नीकर्स','Footwear','Unused surplus',18500,'Off-white low-top canvas shoes, rubber soles and plain laces, adult sizes 6 to 9. Unbranded casual sneakers; matched pairs checked before dispatch.','ऑफ़-व्हाइट लो-टॉप कैनवस जूते, रबर के तलवे और सादे फ़ीते, वयस्क साइज़ 6 से 9। बिना ब्रांड के जूते; भेजने से पहले सही जोड़ी जाँची जाएगी।'],
['phonecase','Silicone phone back covers','सिलिकॉन फ़ोन बैक कवर','Accessories','Unused surplus',2200,'Protective silicone smartphone cases in black clear sage and lavender. Mixed device fits; buyer must verify exact phone model compatibility.','काले, पारदर्शी, सेज और लैवेंडर रंग के सुरक्षा वाले सिलिकॉन स्मार्टफ़ोन कवर। अलग-अलग फ़ोन के लिए; खरीदार सही मॉडल से मेल की जाँच करें।']
].map(([code,title,titleHi,category,condition,reserve,description,descriptionHi],i)=>({code,title,titleHi,category,condition,reserve,description,descriptionHi,photoId:'00000000-0000-4000-8000-'+String(101+i).padStart(12,'0'),image:'/assets/stock/'+code+'.png'}));
export const catalogCities=[
['Jaipur','जयपुर','Rajasthan','राजस्थान'],['Surat','सूरत','Gujarat','गुजरात'],['Delhi','दिल्ली','Delhi','दिल्ली'],['Mumbai','मुंबई','Maharashtra','महाराष्ट्र'],['Bengaluru','बेंगलुरु','Karnataka','कर्नाटक'],['Kolkata','कोलकाता','West Bengal','पश्चिम बंगाल'],['Lucknow','लखनऊ','Uttar Pradesh','उत्तर प्रदेश'],['Guwahati','गुवाहाटी','Assam','असम'],['Hyderabad','हैदराबाद','Telangana','तेलंगाना'],['Chennai','चेन्नई','Tamil Nadu','तमिलनाडु'],['Indore','इंदौर','Madhya Pradesh','मध्य प्रदेश'],['Kochi','कोच्चि','Kerala','केरल'],['Patna','पटना','Bihar','बिहार'],['Bhubaneswar','भुवनेश्वर','Odisha','ओडिशा'],['Ranchi','राँची','Jharkhand','झारखंड'],['Raipur','रायपुर','Chhattisgarh','छत्तीसगढ़'],['Ludhiana','लुधियाना','Punjab','पंजाब'],['Dehradun','देहरादून','Uttarakhand','उत्तराखंड']
].map(([city,cityHi,state,stateHi])=>({city,cityHi,state,stateHi}));
export const stateForCity=city=>catalogCities.find(c=>c.city.toLowerCase()===city.toLowerCase())?.state||'';
export const productForTitle=title=>catalogProducts.find(p=>p.title===title);
export const catalogPhoto=id=>catalogProducts.find(p=>p.photoId===id)?.image;

